# Generated by Django 3.2.16 on 2022-12-26 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20221226_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites',
            options={'ordering': ('favorite',), 'verbose_name': 'Избранное'},
        ),
        migrations.RenameField(
            model_name='favorites',
            old_name='favorites_list',
            new_name='favorite',
        ),
    ]
